#!/bin/bash

arr=(
"The only way to do great work is to love what you do."
"In the middle of every difficulty lies opportunity."
"Don't watch the clock; do what it does. Keep going."
"The future depends on what you do today."
"Believe you can and you're halfway there."
"The only thing we have to fear is fear itself."
"Success is not final, failure is not fatal: It is the courage to continue that counts."
"It does not matter how slowly you go as long as you do not stop."
"The only person you are destined to become is the person you decide to be."
"The best revenge is massive success."
"Your time is limited, don't waste it living someone else's life."
"I can't change the direction of the wind, but I can adjust my sails to always reach my destination."
"You miss 100% of the shots you don't take."
"The way to get started is to quit talking and begin doing."
"The harder the conflict, the greater the triumph."
"The only limit to our realization of tomorrow will be our doubts of today."
"A person who never made a mistake never tried anything new."
"Success is walking from failure to failure with no loss of enthusiasm."
"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment."
"You must be the change you wish to see in the world."
"The future belongs to those who believe in the beauty of their dreams."
"Strive not to be a success, but rather to be of value."
"Don't be afraid to give up the good to go for the great."
"The only way to achieve the impossible is to believe it is possible."
"The power of imagination makes us infinite."
"The journey of a thousand miles begins with one step."
"It always seems impossible until it's done."
"Our greatest glory is not in never falling, but in rising every time we fall."
"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."
"I haven't failed. I've just found 10,000 ways that won't work."
"Dream big and dare to fail."
"Life is 10% what happens to us and 90% how we react to it."
"The best way to predict the future is to create it."
"The only thing standing between you and your dream is the will to try and the belief that it is actually possible."
"Change your thoughts and you change your world."
	)
echo -e "\e[1m\e[31m\e[3m\e[1;47m${arr[$RANDOM%35]}\e[0m"

